name: Setup Node and install Firebase CLI
  install-deps:
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    - name: Install Dependencies
      if: inputs.install-deps == 'true'
      run: yarn install
