name: Setup Node and install Firebase CLI
inputs:
  install-deps:
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'
        cache-dependency-path: './yarn.lock'
    - name: Enable corepack
      shell: bash
      run: corepack enable
    - name: Activate Yarn v4
      shell: bash
      run: corepack prepare yarn@4 --activate
    - name: Install Firebase CLI
      shell: bash
      run: yarn global add firebase-tools
    - name: Install Dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: yarn install --immutable --immutable-cache --non-interactive
