name: Setup Node and install dependencies
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
