name: Setup Node and install dependencies
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'
        cache-dependency-path: './yarn.lock'
    - name: Enable corepack
      shell: bash
      run: corepack enable
    - name: Activate Yarn v4
      shell: bash
      run: corepack prepare yarn@4 --activate
    - name: Install dependencies
      shell: bash
      run: yarn install --immutable --immutable-cache --non-interactive
