# Docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/extension/'
      - '/packages/functions/'
      - '/packages/pwa/'
      - '/packages/rssServer/'
      - '/packages/scripts/'
      - '/packages/shared/'
      - '/packages/sharedClient/'
      - '/packages/sharedServer/'
    schedule:
      interval: 'monthly'
