# Yarn v4 configuration: https://yarnpkg.com/configuration/yarnrc.

nodeLinker: node-modules

# Share a global cache between workspaces.
enableGlobalCache: true

# Opt out of telemetry.
enableTelemetry: false
