name: Shared GitHub action setup
description: Sets up Node.js with Yarn v4 and optionally installs Firebase CLI and project dependencies
inputs:
  install-deps:
    required: false
    default: 'false'
  install-firebase:
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - uses: oven-sh/setup-bun@v2
    - name: Install Firebase CLI
      if: inputs.install-firebase == 'true'
      shell: bash
      run: npm install -g firebase-tools
    - name: Install Dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: bun install
    - name: Version Bun
      shell: bash
      run: bun --version
    - name: Bun workspaces
      shell: bash
      run: bun workspaces list
    - name: List packages
      shell: bash
      run: ls -R packages/
