import * as constantsExports from '@shared/lib/constants';
import * as customIconsExports from '@shared/lib/customIcons';
import * as eventLogExports from '@shared/lib/eventLog';
import * as feedItemsExports from '@shared/lib/feedItems';
import * as firebaseExports from '@shared/lib/firebase';
import * as iconsExports from '@shared/lib/icons';
import * as importQueueExports from '@shared/lib/importQueue';
import * as loggerExports from '@shared/lib/logger';
import * as requestsExports from '@shared/lib/requests';
import * as routerExports from '@shared/lib/router';
import * as themeExports from '@shared/lib/theme';
import * as urlsExports from '@shared/lib/urls';
import * as utilsExports from '@shared/lib/utils';
import * as viewsExports from '@shared/lib/views';

export const constants = constantsExports;
export const customIcons = customIconsExports;
export const eventLog = eventLogExports;
export const feedItems = feedItemsExports;
export const firebase = firebaseExports;
export const icons = iconsExports;
export const importQueue = importQueueExports;
export const logger = loggerExports;
export const requests = requestsExports;
export const router = routerExports;
export const theme = themeExports;
export const urls = urlsExports;
export const utils = utilsExports;
export const views = viewsExports;
