name: Deploy prod Firebase Functions on merge
on:
  # Comment out or remove the push trigger
  # push:
  #   branches:
  #     - master

  # Add a manual trigger instead
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn install
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Create Firebase credentials file
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONDUCTOR_PROD }}' > /tmp/firebase-credentials.json
      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-credentials.json" >> $GITHUB_ENV
      - name: Deploy Firebase Functions
        run: yarn run deploy:functions
