name: Deploy prod Firestore rules on merge
on:
  push:
    branches:
      - main
    paths:
      - 'firestore.rules'
      - '.github/actions/setup-workflow/**'
      - '.github/workflows/firestore-rules-merge.yml'
permissions:
  contents: read
  id-token: write
jobs:
  deploy_firestore_rules_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Common CI setup
        uses: ./.github/actions/setup-workflow
        with:
          install-firebase: 'true'
      - name: Deploy Firestore rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: bun run deploy:rules --project=prod
