name: Deploy staging Firestore indexes on PR
on:
  pull_request:
    paths:
      - 'firestore.indexes.json'
      - '.github/actions/setup-workflow/**'
      - '.github/workflows/firestore-indexes-pull-request.yml'
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  deploy_firestore_indexes_stag:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: CI setup action for Firebase deploy
        uses: ./.github/actions/setup-workflow
        with:
          install-deps: 'true' # TODO: This is not really needed, but CI fails without it.
          install-firebase: 'true'
      - name: Deploy Firestore indexes
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        # Yarn v4 requires installing deps before using `yarn run`, so use `firebase deploy` directly.
        run: firebase deploy --only firestore:indexes --project=stag
