name: Deploy prod Firestore rules on merge
on:
  push:
    branches:
      - master
    paths:
      - 'firestore.rules'
jobs:
  deploy_firestore_rules_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-firebase-deploy
      - name: Deploy Firestore rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn run deploy:rules:firestore --project=prod
