name: Deploy staging Firestore indexes on PR
on:
  pull_request:
    paths:
      - 'firestore.indexes.json'
      - '.github/actions/setup-workflow/**'
      - '.github/workflows/firestore-indexes-pull-request.yml'
permissions:
  contents: read
  id-token: write
jobs:
  deploy_firestore_indexes_stag:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Common CI setup
        uses: ./.github/actions/setup-workflow
        with:
          install-deps: 'true'
          install-firebase: 'true'
      - name: Deploy Firestore indexes
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: bun run deploy:indexes --project=stag
