name: Deploy staging Firestore indexes on PR
on:
  pull_request:
    paths:
      - 'firestore.indexes.json'
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  deploy_firestore_indexes_stag:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy Firestore indexes
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn run deploy:indexes --project=stag
