name: Deploy prod Firestore indexes on merge
on:
  push:
    branches:
      - main
    paths:
      - 'firestore.indexes.json'
      - '.github/actions/setup-workflow/**'
      - '.github/workflows/firestore-indexes-merge.yml'
permissions:
  contents: read
  id-token: write
jobs:
  deploy_firestore_indexes_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: CI setup action for Firebase deploy
        uses: ./.github/actions/setup-workflow
        with:
          install-deps: 'true'
          install-firebase: 'true'
      - name: Deploy Firestore indexes
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: bun run deploy:indexes --project=prod
