name: Preview staging PWA on PR
on:
  pull_request:
    paths:
      - 'packages/pwa/**'
      - 'packages/shared/**'
      - '.firebaserc'
      - '.prettierrc'
      - 'eslint.config.mjs'
      - 'firebase.json'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  preview_hosting_stag:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-firebase-deploy
        with:
          install-deps: 'true'
      - name: Build PWA
        run: yarn run build:pwa
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
      - name: Deploy PWA
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONDUCTOR_STAG }}
          projectId: conductor-stag
