name: Deploy prod Firebase rules on merge
on:
  push:
    branches:
      - master
    paths:
      - 'firestore.rules'
      - 'storage.rules'
jobs:
  deploy_rules_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy Firebase rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn run deploy:rules --project=prod
