name: Deploy prod Functions on merge
on:
  push:
    branches:
      - master
    paths:
      - 'packages/{functions,shared}/**'
      - '.firebaserc'
      - '.prettierrc'
      - 'eslint.config.mjs'
      - 'firebase.json'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'
      - '.github/actions/setup-firebase-deploy/**'
      - '.github/workflows/firebase-functions-merge.yml'
jobs:
  deploy_functions_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: CI setup action for Firebase deploy
        uses: ./.github/actions/setup-firebase-deploy
        with:
          install-deps: 'true'
      - name: Build functions
        run: yarn run build:functions
      - name: Create .env file
        working-directory: packages/functions
        env:
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
        run: |
          if [ -z "$FIRECRAWL_API_KEY" ]; then
            echo "Error: FIRECRAWL_API_KEY secret must be added in GitHub"
            exit 1
          fi
          echo "FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}" > .env.conductor-prod
      - name: Deploy Firebase Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn run deploy:functions --project=prod
