name: Deploy prod PWA on merge
on:
  push:
    branches:
      - main
    paths:
      - 'packages/pwa/**'
      - 'packages/shared/**'
      - 'packages/sharedClient/**'
      - '.firebaserc'
      - '.prettierrc'
      - 'eslint.config.mjs'
      - 'firebase.json'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'
      - '.github/actions/setup-workflow/**'
      - '.github/workflows/firebase-hosting-merge.yml'
permissions:
  contents: read
  id-token: write
  checks: write
jobs:
  deploy_hosting_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: CI setup action for Firebase deploy
        uses: ./.github/actions/setup-workflow
        with:
          install-deps: 'true'
          install-firebase: 'true'
      - name: Validate PWA
        run: yarn run validate:pwa
      - name: Build PWA
        run: yarn run build:pwa
        env:
          VITE_CONDUCTOR_URL: ${{ secrets.VITE_CONDUCTOR_URL }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
      - name: Deploy PWA
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONDUCTOR_PROD }}
          channelId: live
          projectId: conductor-prod
