name: Deploy prod Functions on merge
on:
  push:
    branches:
      - master
jobs:
  deploy_functions_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn install
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy Firebase Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
        run: yarn run deploy:functions --project=prod
