name: Deploy prod Firestore indexes on merge
on:
  push:
    branches:
      - master
    paths:
      - 'firestore.indexes.json'
      - '.github/actions/setup-firebase-deploy/**'
      - '.github/workflows/firestore-indexes-merge.yml'
jobs:
  deploy_firestore_indexes_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: CI setup action for Firebase deploy
        uses: ./.github/actions/setup-firebase-deploy
      - name: Deploy Firestore indexes
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn run deploy:indexes --project=prod
