name: Deploy staging Firestore indexes on PR
on:
  pull_request:
    paths:
      - 'firestore.indexes.json'
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  deploy_firestore_indexes_stag:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: ./.github/actions/setup-firebase-deploy
      - name: Deploy Firestore indexes
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn run deploy:indexes --project=stag
