name: Deploy prod Cloud Storage rules on merge
on:
  push:
    branches:
      - master
    paths:
      - 'storage.rules'
      - '.github/workflows/storage-rules-merge.yml'
jobs:
  deploy_storage_rules_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: CI setup action for Firebase deploy
        uses: ./.github/actions/setup-firebase-deploy
      - name: Deploy Cloud Storage rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn run deploy:rules:storage --project=prod
