name: Deploy staging Cloud Storage rules on PR
on:
  pull_request:
    paths:
      - 'storage.rules'
      - '.github/actions/setup-workflow/**'
      - '.github/workflows/storage-rules-pull-request.yml'
permissions:
  contents: read
  id-token: write
jobs:
  deploy_storage_rules_stag:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Common CI setup
        uses: ./.github/actions/setup-workflow
        with:
          install-firebase: 'true'
      - name: Deploy Cloud Storage rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: bun run deploy:rules --project=stag
