name: Deploy prod Cloud Storage rules on merge
on:
  push:
    branches:
      - master
    paths:
      - 'storage.rules'
      - '.github/actions/setup-workflow/**'
      - '.github/workflows/storage-rules-merge.yml'
jobs:
  deploy_storage_rules_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: CI setup action for Firebase deploy
        uses: ./.github/actions/setup-workflow
        with:
          install-firebase: 'true'
      - name: Deploy Cloud Storage rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        # Yarn v4 requires installing deps before using `yarn run`, so use `firebase deploy` directly.
        run: firebase deploy --only storage --project=prod
