name: Deploy staging Cloud Storage rules on PR
on:
  pull_request:
    paths:
      - 'storage.rules'
      - '.github/actions/setup-firebase-deploy/**'
      - '.github/workflows/storage-rules-pull-request.yml'
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  deploy_storage_rules_stag:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: CI setup action for Firebase deploy
        uses: ./.github/actions/setup-firebase-deploy
        with:
          install-deps: 'true' # TODO: This is not really needed, but CI fails without it.
      - name: Deploy Cloud Storage rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn run deploy:rules:storage --project=stag
