name: Run tests on push
on: [push]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Common CI setup
        uses: ./.github/actions/setup-workflow
        with:
          install-deps: 'true'
      - name: Run tests
        run: bun test
