name: Run validate on push
on: [push]
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: CI setup for bun
        uses: ./.github/actions/setup-workflow
        with:
          install-deps: 'true'
      - name: Validate format
        run: bun run validate:format
      - name: Validate lint
        run: bun run validate:lint
      # - name: Validate unused exports and deps
      # run: bun run validate:knip
      - name: Validate types
        run: bun run validate:types
